modLoader="javafml"
loaderVersion="[34,)"
license="The Unlicense"

[[mods]]
    modId="habitats"
    version="${file.jarVersion}"
    displayName="Habitats Mod"
    #updateJSONURL="http://myurl.me/" #optional
    #displayURL="http://example.com/" #optional
    #logoFile="examplemod.png" #optional
    credits="Thanks for this example mod goes to Java" #optional
    authors="@Praaly & @Nalikk" #optional
    description='''
    Habitats Mod by @Praaly & @Nalikk

    Alpha Version
    '''

[[dependencies.habitats]]
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.habitats]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3,1.17)"
    ordering="NONE"
    side="BOTH"
